#!/usr/bin/env python
import fcntl
import os
import os.path as path
import signal
import subprocess as sub
import sys
import threading

class Fucked(Exception): pass

def ensure(condition, msg):
    if not condition:
        raise Fucked(msg)


def log(string):
    sys.stderr.write(string + '\n')


def cqfile(*args):
    return path.join(cqdir, *args)


def wakeup():
    event.acquire()
    event.notify()
    event.release()


def halt():
    global stop_flag
    stop_flag = True
    wakeup()


def lock(fd): fcntl.flock(fd, fcntl.LOCK_EX)
def unlock(fd): fcntl.flock(fd, fcntl.LOCK_UN)


def popline(filename):
    with open(filename, 'r') as readf:
        line = readf.readline()
        with open(filename, 'w') as writef:
            writef.write(readf.read())
        return line[:-1]        # remove trailing newline


def run_job(job_dir):
    run_path = path.join(job_dir, 'run')
    pid_path = path.join(job_dir, 'pid')
    lock_path = path.join(job_dir, 'lock')

    with open('/dev/null', 'w') as nullfd:
        child = sub.Popen(
            ['screen',
             '-D', '-m',        # start detached, but don't fork a new process
             '-S', 'cqd',       # give it a useful session name
             '--', run_path],   # run the given job
            stdin=nullfd, stdout=nullfd, stderr=None,
            close_fds=True)

        # Write the pid to the pidfile
        log('spawned child %d running %s' % (child.pid, run_path))

        with open(pid_path, 'w') as pidfile:
            pidfile.write("%d\n" % child.pid)

        # Wait for the child to die
        status = child.wait()
        log("child %d succeeded" % child.pid
            if not status else
            "child %d failed with status %d" % (child.pid, status))

        # Clean up after ourselves.
        status = sub.Popen(['rm', '-r', '--', job_dir]).wait()
        ensure(not status, "could not remove job directory %s" % job_dir)


def handle_job():
    lock(lock_file)
    jobfd = None
    try:
        queue_path = cqfile('queue')
        # If the file is empty, do nothing.
        if not (path.exists(queue_path) and os.stat(queue_path).st_size):
            return False

        # Take a job from the queue and make it current
        job = popline(queue_path)
        job_dir = cqfile('jobs', job)
        with open(cqfile('jobs', job, 'lock')) as job_lock_file:
            lock(job_lock_file)
            try:
                os.rename(job_dir, cqfile('current'))
            finally:
                unlock(job_lock_file)
    finally:
        unlock(lock_file)

    # Run the job
    run_job(cqfile('current'))
    return True


def event_loop():
    # Yes, each of these checks is necessary. Yes, this is ugly. What I really
    # want is a saturating binary semaphore.
    while not stop_flag:
        while handle_job() and not stop_flag:
            continue
        if stop_flag:
            break
        event.acquire()
        event.wait()
        event.release()

    # Exit gracefully
    log("exiting")
    os.remove(cqfile('cqd.pid'))


def main(argv):
    global cqdir, lock_file, stop_flag, event

    stop_flag = False

    try: cqdir = os.environ["CQDIR"]
    except KeyError:
        raise UserError("CQDIR not set")

    ensure(path.isdir(cqdir), "CQDIR is not a dir")
    ensure(os.access(cqdir, os.F_OK | os.R_OK | os.W_OK | os.X_OK),
           "CQDIR does not have acceptable permissions")

    lock_file = open(cqfile('lock'), 'w')

    # Register signal handlers for USR1, USR2
    signal.signal(signal.SIGUSR1, lambda signo, frame: wakeup())
    signal.signal(signal.SIGUSR2, lambda signo, frame: halt())

    # Run the event loop
    event = threading.Condition()
    threading.Thread(target=event_loop).start()

    # Wait for signals.
    while not stop_flag:
        signal.pause()


if __name__ == "__main__":
    try:
        main(sys.argv)
    except Fucked, e:
        log(e)
        exit(1)
    except:
        # Something weird happened, so exit.
        halt()
        raise
